# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-31 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170731_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u535a\u5ba2\u6807\u7b7e', 'verbose_name_plural': '\u535a\u5ba2\u6807\u7b7e'},
        ),
        migrations.RenameField(
            model_name='blogspost',
            old_name='body',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
