# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170731_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='tag',
            field=models.ManyToManyField(related_name='t_blog', to='blog.Tag'),
        ),
    ]
