# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170807_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
