# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-09 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170807_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='r',
            field=models.IntegerField(default=0, verbose_name=b'dw'),
        ),
    ]
