# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-13 05:48
from __future__ import unicode_literals

# import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_userprofile_address'),
    ]

    operations = [

    ]
