# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-16 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170816_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 16, 14, 59, 38, 381000, tzinfo=utc), verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=False,
        ),
    ]
