# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-16 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogspost_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogspost',
            old_name='timestamp',
            new_name='publish_time',
        ),
    ]
