# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170816_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=datetime.datetime(2017, 8, 23, 5, 49, 16, 630000, tzinfo=utc), upload_to=b'static/media/user_image'),
            preserve_default=False,
        ),
    ]
