# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170823_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=b'media/user_image'),
        ),
    ]
