# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grades',
            new_name='xuehao',
        ),
    ]
