# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20170721_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='cj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuwen', models.CharField(max_length=30)),
                ('shuxue', models.CharField(max_length=30)),
                ('yingyu', models.CharField(max_length=30)),
                ('zonghe', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
