# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20170721_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuwen', models.CharField(max_length=30)),
                ('shuxue', models.CharField(max_length=30)),
                ('yingyu', models.CharField(max_length=30)),
                ('zonghe', models.CharField(max_length=30)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_grades', to='wechat.student')),
            ],
        ),
        migrations.DeleteModel(
            name='cj',
        ),
    ]
