# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-21 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20170721_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grades',
            new_name='grade',
        ),
    ]
