# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20170721_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='s',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s_grades', to='wechat.student'),
        ),
    ]
