# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0011_auto_20170723_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '\u5b66\u751f\u6210\u7ee9', 'verbose_name_plural': '\u5b66\u751f\u6210\u7ee9'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '\u5b66\u751f\u4fe1\u606f', 'verbose_name_plural': '\u5b66\u751f\u4fe1\u606f'},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='s',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='grade',
            name='shuxue',
            field=models.CharField(max_length=30, verbose_name='\u6570\u5b66'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='yingyu',
            field=models.CharField(max_length=30, verbose_name='\u82f1\u8bed'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='yuwen',
            field=models.CharField(max_length=30, verbose_name='\u8bed\u6587'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='zonghe',
            field=models.CharField(max_length=30, verbose_name='\u7efc\u5408'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='open_id',
            field=models.CharField(max_length=30, verbose_name='\u5fae\u4fe1id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xuehao',
            field=models.CharField(max_length=30, verbose_name='\u5b66\u53f7'),
        ),
    ]
